#!/usr/bin/env node
/* =============================================================================
   tools/build.js — static page generator
   -----------------------------------------------------------------------------
   Turns every listing in assets/data/jobs.json into its own crawlable HTML
   page so each job has a unique, indexable URL:

       /remote-jobs/<slug>.html

   It also rewrites sitemap.xml so those URLs are submitted to search engines.

   Run it after every change to jobs.json:

       node tools/build.js

   Nothing is installed and nothing is bundled — this only writes HTML.
   Branding, domain, categories and the output folder all come from
   assets/js/config.js, which stays the single source of truth.
   ========================================================================== */

'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const MARKER = '<!-- Generated by tools/build.js — edits here are overwritten. -->';

/* =============================================================================
   1. Load config.js and app.js without duplicating their contents
   ========================================================================== */
function readFile(rel) {
  return fs.readFileSync(path.join(ROOT, rel), 'utf8');
}

function loadConfig() {
  const code = readFile('assets/js/config.js');
  const sandbox = {};
  vm.runInNewContext(
    code + '\n;globalThis.__exports = { SITE_CONFIG, CATEGORIES };',
    sandbox,
    { filename: 'config.js' }
  );
  return sandbox.__exports;
}

/** Reuse the icon set from app.js so generated markup matches the live UI. */
function loadIcons() {
  const code = readFile('assets/js/app.js');
  const match = code.match(/const ICONS = (\{[\s\S]*?\n {2}\});/);
  if (!match) {
    console.warn('! Could not read ICONS from app.js — icons will be added by JS only.');
    return {};
  }
  try {
    return vm.runInNewContext('(' + match[1] + ')');
  } catch (err) {
    console.warn('! ICONS block in app.js could not be parsed:', err.message);
    return {};
  }
}

const { SITE_CONFIG, CATEGORIES } = loadConfig();
const ICONS = loadIcons();

const SITE_URL = String(SITE_CONFIG.url || '').replace(/\/+$/, '');
const JOB_DIR = String((SITE_CONFIG.jobPages && SITE_CONFIG.jobPages.dir) || 'remote-jobs')
  .replace(/^\/+|\/+$/g, '');
const CLEAN_URLS = !!(SITE_CONFIG.seo && SITE_CONFIG.seo.cleanUrls);
const OUT_DIR = path.join(ROOT, JOB_DIR);

/* =============================================================================
   2. Small helpers — ports of the matching functions in app.js / jobs.js
   ========================================================================== */
const ENT = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
const esc = (v) => (v === null || v === undefined ? '' : String(v).replace(/[&<>"']/g, (c) => ENT[c]));

function slugify(str) {
  return String(str).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function truncate(str, max) {
  const s = String(str || '').trim();
  if (s.length <= max) return s;
  return s.slice(0, max - 1).replace(/\s+\S*$/, '') + '…';
}

function initials(name) {
  const parts = String(name || '').replace(/[^A-Za-z0-9 ]/g, ' ').split(/\s+/).filter(Boolean);
  if (!parts.length) return '–';
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[1][0]).toUpperCase();
}

function hueFor(name) {
  let h = 0;
  const s = String(name || '');
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) % 360;
  return h;
}

function formatDate(value) {
  const d = value ? new Date(value) : null;
  if (!d || isNaN(d.getTime())) return '';
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' });
}

function isoDate(value) {
  const d = value ? new Date(value) : null;
  if (!d || isNaN(d.getTime())) return '';
  return d.toISOString().slice(0, 10);
}

function safeUrl(value) {
  if (!value) return '';
  try {
    const u = new URL(String(value));
    return u.protocol === 'http:' || u.protocol === 'https:' ? u.href : '';
  } catch (err) {
    return '';
  }
}

function icon(name, cls) {
  const body = ICONS[name];
  if (!body) return '';
  return '<svg class="icon' + (cls ? ' ' + cls : '') + '" viewBox="0 0 24 24" aria-hidden="true" focusable="false">' + body + '</svg>';
}

const asArray = (v) => (Array.isArray(v) ? v.filter((x) => typeof x === 'string' && x.trim()) : []);

/* Root-relative path -> path usable from inside the job folder. */
const up = (p) => '../' + String(p || '').replace(/^\/+/, '');
const absUrl = (p) => SITE_URL + '/' + String(p || '').replace(/^\/+/, '');

/* The address search engines should index. Cloudflare Pages serves every page
   without its .html and redirects /jobs.html -> /jobs, so pointing a canonical
   at the .html would point it at a redirect. Links inside the site keep the
   .html — they still work when the folder is opened locally. */
function canonicalUrl(p) {
  let out = String(p || '').replace(/^\/+/, '');
  if (CLEAN_URLS) {
    out = out.replace(/\.html(?=$|[?#])/, '');
    if (out === 'index' || out.indexOf('index?') === 0) out = out.slice(5);
  }
  return absUrl(out);
}

/* Root-relative link path, .html kept (used for hrefs and for _redirects). */
const linkPath = (p) => (CLEAN_URLS ? String(p).replace(/\.html(?=$|[?#])/, '') : String(p));

/* =============================================================================
   3. Normalise listings — mirrors Jobs.normalize() in assets/js/jobs.js
   ========================================================================== */
function jobSlug(job) {
  if (job.slug) return slugify(job.slug).slice(0, 120);
  const title = slugify(job.title).slice(0, 70).replace(/-+$/, '');
  const company = slugify(job.company).slice(0, 40).replace(/-+$/, '');
  const id = slugify(job.id);
  return [title, company ? 'at-' + company : '', id].filter(Boolean).join('-');
}

function normalize(raw, index) {
  const job = {
    id: String(raw.id || '').trim() || 'job-' + index,
    demo: raw.demo === true,
    title: String(raw.title || 'Untitled role').trim(),
    company: String(raw.company || 'Undisclosed company').trim(),
    companyLogo: safeUrl(raw.companyLogo),
    location: String(raw.location || '').trim(),
    country: String(raw.country || '').trim(),
    remote: raw.remote !== false,
    jobType: String(raw.jobType || '').trim(),
    category: slugify(raw.category || 'other'),
    experience: String(raw.experience || '').trim(),
    salary: String(raw.salary || '').trim(),
    salaryMin: Number(raw.salaryMin) || 0,
    salaryMax: Number(raw.salaryMax) || 0,
    salaryCurrency: String(raw.salaryCurrency || '').trim(),
    salaryPeriod: String(raw.salaryPeriod || '').trim().toUpperCase(),
    postedDate: String(raw.postedDate || '').trim(),
    validThrough: String(raw.validThrough || '').trim(),
    description: String(raw.description || '').trim(),
    responsibilities: asArray(raw.responsibilities),
    requirements: asArray(raw.requirements),
    benefits: asArray(raw.benefits),
    skills: asArray(raw.skills),
    applyUrl: safeUrl(raw.applyUrl),
    source: String(raw.source || '').trim(),
    featured: raw.featured === true,
    status: String(raw.status || 'active').trim().toLowerCase(),
    slug: String(raw.slug || '').trim()
  };
  job.slug = jobSlug(job);
  job.pageUrl = JOB_DIR + '/' + job.slug + '.html'; // the file, and every href
  job.file = job.pageUrl;
  return job;
}

function categoryMeta(slug) {
  return (
    CATEGORIES.find((c) => c.slug === slug) || {
      slug: slug,
      name: slug ? slug.replace(/-/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase()) : 'Other',
      icon: 'briefcase',
      blurb: '',
      intro: ''
    }
  );
}

/** Same scoring as Jobs.related() so the static block matches the live one. */
function relatedJobs(all, job, limit) {
  const skills = new Set(job.skills.map((s) => s.toLowerCase()));
  return all
    .filter((j) => j.id !== job.id)
    .map((j) => {
      let score = 0;
      if (j.category === job.category) score += 50;
      if (j.jobType === job.jobType) score += 12;
      if (j.experience === job.experience) score += 6;
      if (j.country === job.country) score += 4;
      j.skills.forEach((s) => {
        if (skills.has(s.toLowerCase())) score += 8;
      });
      return { job: j, score: score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || dateValue(b.job.postedDate) - dateValue(a.job.postedDate))
    .slice(0, limit || SITE_CONFIG.listing.relatedJobs)
    .map((x) => x.job);
}

function dateValue(v) {
  const d = v ? new Date(v) : null;
  return d && !isNaN(d.getTime()) ? d.getTime() : 0;
}

/* =============================================================================
   4. Structured data (JSON-LD)
   ========================================================================== */
/** Google asks for the description in HTML — lists included. */
function schemaDescription(job) {
  const block = (heading, items) =>
    items.length
      ? '<h3>' + esc(heading) + '</h3><ul>' + items.map((i) => '<li>' + esc(i) + '</li>').join('') + '</ul>'
      : '';
  return (
    '<p>' + esc(job.description) + '</p>' +
    block('Responsibilities', job.responsibilities) +
    block('Requirements', job.requirements) +
    block('Benefits', job.benefits)
  );
}

/* A JobPosting is only emitted for real listings. Sample/demo rows and every
   missing field are left out rather than invented — fabricated job markup is
   a structured-data violation and gets sites penalised. */
function jobPostingSchema(job) {
  if (!SITE_CONFIG.features.structuredData) return null;
  if (SITE_CONFIG.demoMode || job.demo) return null;
  if (!job.title || !job.company || !job.postedDate) return null;

  const data = {
    '@context': 'https://schema.org',
    '@type': 'JobPosting',
    title: job.title,
    description: schemaDescription(job),
    datePosted: job.postedDate,
    url: canonicalUrl(job.pageUrl),
    hiringOrganization: { '@type': 'Organization', name: job.company },
    identifier: { '@type': 'PropertyValue', name: job.company, value: job.id }
  };

  if (job.validThrough) data.validThrough = job.validThrough;
  if (job.jobType) {
    const map = {
      'full-time': 'FULL_TIME',
      'part-time': 'PART_TIME',
      contract: 'CONTRACTOR',
      freelance: 'CONTRACTOR',
      internship: 'INTERN',
      temporary: 'TEMPORARY'
    };
    const key = job.jobType.toLowerCase();
    if (map[key]) data.employmentType = map[key];
  }
  if (job.companyLogo) data.hiringOrganization.logo = job.companyLogo;

  if (job.remote) {
    data.jobLocationType = 'TELECOMMUTE';
    if (job.country && job.country !== 'Worldwide') {
      data.applicantLocationRequirements = { '@type': 'Country', name: job.country };
    }
  } else if (job.country) {
    data.jobLocation = {
      '@type': 'Place',
      address: { '@type': 'PostalAddress', addressCountry: job.country }
    };
  }

  if (job.salaryMin > 0 && job.salaryCurrency && job.salaryPeriod) {
    const value = { '@type': 'QuantitativeValue', unitText: job.salaryPeriod };
    if (job.salaryMax > job.salaryMin) {
      value.minValue = job.salaryMin;
      value.maxValue = job.salaryMax;
    } else {
      value.value = job.salaryMin;
    }
    data.baseSalary = { '@type': 'MonetaryAmount', currency: job.salaryCurrency, value: value };
  }

  if (job.skills.length) data.skills = job.skills.join(', ');
  if (job.requirements.length) data.qualifications = job.requirements.join(' ');
  if (job.responsibilities.length) data.responsibilities = job.responsibilities.join(' ');
  if (job.benefits.length) data.jobBenefits = job.benefits.join(' ');
  if (job.experience) data.experienceRequirements = job.experience;
  if (job.category) data.occupationalCategory = categoryMeta(job.category).name;
  if (job.applyUrl) data.directApply = false; // the employer's site takes the application

  return data;
}

function breadcrumbSchema(job) {
  const cat = categoryMeta(job.category);
  const items = [
    ['Home', canonicalUrl('index.html')],
    ['Remote Jobs', canonicalUrl('jobs.html')],
    [cat.name, canonicalUrl('category.html?category=' + encodeURIComponent(cat.slug))],
    [job.title + ' at ' + job.company, canonicalUrl(job.pageUrl)]
  ];
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((pair, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: pair[0],
      item: pair[1]
    }))
  };
}

const jsonLd = (id, data) =>
  data ? '<script type="application/ld+json" id="' + id + '">' + JSON.stringify(data).replace(/</g, '\\u003c') + '</script>' : '';

/* =============================================================================
   5. Page chrome — lifted from job.html so the generated pages never drift
   ========================================================================== */
function liftChrome() {
  const src = readFile('job.html');
  const headerStart = src.indexOf('<a class="skip-link"');
  const mainStart = src.indexOf('<main id="main">');
  const mainEnd = src.indexOf('</main>');
  const scriptStart = src.indexOf('<script src="assets/js/config.js"');
  if (headerStart < 0 || mainStart < 0 || mainEnd < 0 || scriptStart < 0) {
    throw new Error('job.html no longer has the expected structure — update tools/build.js.');
  }
  const footerStart = src.indexOf('<footer class="site-footer">');
  return {
    header: rewritePaths(src.slice(headerStart, mainStart)),
    footer: rewritePaths(src.slice(footerStart, scriptStart)),
    scripts: rewritePaths(src.slice(scriptStart, src.indexOf('</body>')))
  };
}

/* The generated pages sit one folder down, so same-folder links need ../ */
function rewritePaths(html) {
  return html.replace(/(href|src)="(?!https?:|\/\/|\/|#|\.\.\/|mailto:|tel:|data:)([^"]+)"/g, (m, attr, url) => attr + '="../' + url + '"');
}

/* =============================================================================
   6. Job page body — mirrors renderJob() in assets/js/ui.js
   ========================================================================== */
function logoHTML(job, size) {
  const cls = 'company-logo' + (size ? ' company-logo--' + size : '');
  if (job.companyLogo) {
    return '<img class="' + cls + '" src="' + esc(job.companyLogo) + '" alt="' + esc(job.company + ' logo') +
      '" loading="lazy" decoding="async" width="56" height="56">';
  }
  return '<span class="' + cls + '" style="--logo-hue:' + hueFor(job.company) + '" aria-hidden="true">' +
    esc(initials(job.company)) + '</span>';
}

function metaHTML(job) {
  const items = [];
  if (job.location) items.push(['pin', job.location]);
  if (job.jobType) items.push(['briefcase', job.jobType]);
  if (job.salary) items.push(['wallet', job.salary]);
  return '<ul class="meta-list">' + items
    .map((it) => '<li class="meta-list__item">' + icon(it[0]) + '<span>' + esc(it[1]) + '</span></li>')
    .join('') + '</ul>';
}

function saveButtonHTML(job, variant) {
  if (!SITE_CONFIG.features.savedJobs) return '';
  const cls = 'save-btn' + (variant ? ' save-btn--' + variant : '');
  return '<button type="button" class="' + cls + '" data-save-job="' + esc(job.id) + '" aria-pressed="false"' +
    ' aria-label="' + esc('Save job: ' + job.title) + '">' + icon('bookmark') +
    (variant === 'wide' ? '<span class="save-btn__text">Save Job</span>' : '') + '</button>';
}

function applyButtonHTML(job, extraClass) {
  const cls = 'btn btn--primary ' + (extraClass || 'btn--lg') + ' btn--apply';
  if (job.applyUrl) {
    return '<a class="' + cls + '" href="' + esc(job.applyUrl) + '" target="_blank" rel="noopener noreferrer nofollow">' +
      'Apply on Employer Website' + icon('external') + '</a>';
  }
  return '<button type="button" class="' + cls + '" disabled aria-disabled="true">Application link unavailable</button>';
}

function applyBlockHTML(job, compact) {
  const note = job.applyUrl
    ? 'This button opens the employer’s own application page in a new tab. ' + SITE_CONFIG.name +
      ' is not the employer and does not collect applications.'
    : 'This is a sample listing used to demonstrate the site. There is no application link and no vacancy behind it.';
  return (
    (compact
      ? '<h2 class="side-card__title">Apply for this job</h2>'
      : '<h2 class="detail-block__title">How to apply</h2>') +
    applyButtonHTML(job) +
    '<p class="apply-note">' + esc(note) + '</p>'
  );
}

function listBlock(title, items) {
  if (!items.length) return '';
  return '<section class="detail-block">' +
    '<h2 class="detail-block__title">' + esc(title) + '</h2>' +
    '<ul class="tick-list">' +
      items.map((i) => '<li>' + icon('check') + '<span>' + esc(i) + '</span></li>').join('') +
    '</ul>' +
  '</section>';
}

function cardHTML(job) {
  const cat = categoryMeta(job.category);
  const href = up(job.pageUrl);
  const badges = [];
  if (job.featured) badges.push('<span class="badge badge--featured">Featured</span>');
  if (job.remote) badges.push('<span class="badge badge--remote">Remote</span>');
  if (job.demo) badges.push('<span class="badge badge--demo" title="Sample listing for demonstration">Demo</span>');

  return '<article class="job-card job-card--compact" data-job-id="' + esc(job.id) + '">' +
      '<div class="job-card__top">' +
        logoHTML(job) +
        '<div class="job-card__headings">' +
          '<h3 class="job-card__title"><a href="' + esc(href) + '">' + esc(job.title) + '</a></h3>' +
          '<p class="job-card__company">' + icon('building') + '<span>' + esc(job.company) + '</span></p>' +
        '</div>' +
        saveButtonHTML(job) +
      '</div>' +
      (badges.length ? '<div class="badge-row">' + badges.join('') + '</div>' : '') +
      metaHTML(job) +
      '<div class="job-card__foot">' +
        '<div class="job-card__tags">' +
          '<a class="tag tag--link" href="' + esc(up('category.html?category=' + encodeURIComponent(cat.slug))) + '">' + esc(cat.name) + '</a>' +
          (job.experience ? '<span class="tag">' + esc(job.experience) + '</span>' : '') +
          '<span class="tag tag--muted">' + icon('clock') + esc(formatDate(job.postedDate)) + '</span>' +
        '</div>' +
        '<a class="btn btn--sm btn--primary job-card__cta" href="' + esc(href) + '" aria-label="' +
          esc('View job: ' + job.title + ' at ' + job.company) + '">View Job' + icon('arrowRight') + '</a>' +
      '</div>' +
    '</article>';
}

function detailHTML(job) {
  const badges = [];
  if (job.remote) badges.push('<span class="badge badge--remote">Remote</span>');
  if (job.jobType) badges.push('<span class="badge">' + esc(job.jobType) + '</span>');
  if (job.experience) badges.push('<span class="badge">' + esc(job.experience) + '</span>');
  if (job.demo) badges.push('<span class="badge badge--demo">Demo listing</span>');

  return '<header class="detail-head">' +
      '<div class="detail-head__top">' +
        logoHTML(job, 'lg') +
        '<div>' +
          '<h1 class="detail-head__title">' + esc(job.title) + '</h1>' +
          '<p class="detail-head__company">' +
            '<span class="detail-head__org">' + esc(job.company) + '</span>' +
            (job.location ? '<span class="meta-inline">' + icon('pin') + esc(job.location) + '</span>' : '') +
            '<span class="meta-inline">' + icon('clock') + 'Posted ' +
              '<time datetime="' + esc(isoDate(job.postedDate)) + '">' + esc(formatDate(job.postedDate)) + '</time>' +
            '</span>' +
          '</p>' +
        '</div>' +
      '</div>' +
      '<div class="badge-row">' + badges.join('') + '</div>' +
    '</header>' +

    '<div class="ad-slot ad-slot--detail-top" data-ad="header"></div>' +

    '<section class="detail-block">' +
      '<h2 class="detail-block__title">About this role</h2>' +
      '<p class="detail-block__text">' + esc(job.description) + '</p>' +
    '</section>' +
    listBlock('Responsibilities', job.responsibilities) +
    listBlock('Requirements', job.requirements) +
    listBlock('Benefits', job.benefits) +
    (job.skills.length
      ? '<section class="detail-block">' +
          '<h2 class="detail-block__title">Skills</h2>' +
          '<div class="job-card__tags">' +
            job.skills.map((s) => '<span class="tag">' + esc(s) + '</span>').join('') +
          '</div>' +
        '</section>'
      : '') +

    '<section class="detail-block detail-block--apply">' + applyBlockHTML(job) + '</section>' +

    '<div class="ad-slot ad-slot--detail-bottom" data-ad="footer"></div>';
}

function sidebarHTML(job) {
  const cat = categoryMeta(job.category);
  const summary = [
    ['briefcase', 'Job type', job.jobType],
    ['pin', 'Location', job.location],
    ['globe', 'Work setting', job.remote ? 'Remote' : 'On-site / hybrid'],
    ['wallet', 'Salary', job.salary],
    ['trending', 'Experience', job.experience],
    ['clock', 'Posted', formatDate(job.postedDate)]
  ].filter((row) => !!row[2]);

  return '<div class="side-card side-card--apply">' +
      applyBlockHTML(job, true) + saveButtonHTML(job, 'wide') +
    '</div>' +
    '<div class="side-card">' +
      '<h2 class="side-card__title">Job summary</h2>' +
      '<dl class="summary-list">' +
        summary.map((row) =>
          '<div class="summary-list__row">' +
            '<dt>' + icon(row[0]) + esc(row[1]) + '</dt>' +
            '<dd>' + esc(row[2]) + '</dd>' +
          '</div>').join('') +
        '<div class="summary-list__row">' +
          '<dt>' + icon('briefcase') + 'Category</dt>' +
          '<dd><a href="' + esc(up('category.html?category=' + encodeURIComponent(cat.slug))) + '">' + esc(cat.name) + '</a></dd>' +
        '</div>' +
      '</dl>' +
    '</div>' +
    '<div class="side-card">' +
      '<h2 class="side-card__title">Share this job</h2>' +
      '<div class="share-row" data-share></div>' +
    '</div>' +
    '<div class="ad-slot ad-slot--sidebar" data-ad="sidebar"></div>';
}

function breadcrumbHTML(job) {
  const cat = categoryMeta(job.category);
  return '<a href="' + esc(up('index.html')) + '">Home</a>' + icon('arrowRight') +
    '<a href="' + esc(up('jobs.html')) + '">Jobs</a>' + icon('arrowRight') +
    '<a href="' + esc(up('category.html?category=' + encodeURIComponent(cat.slug))) + '">' + esc(cat.name) + '</a>' +
    icon('arrowRight') + '<span aria-current="page">' + esc(truncate(job.title, 44)) + '</span>';
}

/* =============================================================================
   7. The full page
   ========================================================================== */
function pageHTML(job, all, chrome) {
  const cat = categoryMeta(job.category);
  const heading = job.title + ' at ' + job.company;
  const title = SITE_CONFIG.seo.titleTemplate.replace('%s', heading);
  /* Same formula as RW.setMeta() in ui.js, so the client-side pass that runs
     after load writes back exactly the same description. */
  const description = truncate(
    job.title + ' at ' + job.company + '. ' + (job.location ? job.location + '. ' : '') + job.description,
    155
  );
  const canonical = canonicalUrl(job.pageUrl);
  const ogImage = absUrl(SITE_CONFIG.seo.defaultImage);
  const robots = SITE_CONFIG.demoMode
    ? 'noindex, nofollow'
    : 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1';
  const related = relatedJobs(all, job);
  const twitter = SITE_CONFIG.seo.twitterHandle;

  return '<!DOCTYPE html>\n' +
'<html lang="en" data-base="../">\n' +
'<head>\n' +
MARKER + '\n' +
'<meta charset="utf-8">\n' +
'<meta name="viewport" content="width=device-width, initial-scale=1">\n' +
'<script>document.documentElement.className += " js";</script>\n' +
'<title>' + esc(title) + '</title>\n' +
'<meta name="description" content="' + esc(description) + '">\n' +
'<meta name="robots" content="' + robots + '">\n' +
'<link rel="canonical" href="' + esc(canonical) + '">\n' +
'<meta name="theme-color" content="#2563EB">\n' +
'<meta name="format-detection" content="telephone=no">\n' +
'\n' +
'<!-- Open Graph -->\n' +
'<meta property="og:type" content="article">\n' +
'<meta property="og:site_name" content="' + esc(SITE_CONFIG.name) + '">\n' +
'<meta property="og:locale" content="' + esc(SITE_CONFIG.seo.locale) + '">\n' +
'<meta property="og:title" content="' + esc(title) + '">\n' +
'<meta property="og:description" content="' + esc(description) + '">\n' +
'<meta property="og:url" content="' + esc(canonical) + '">\n' +
'<meta property="og:image" content="' + esc(ogImage) + '">\n' +
'<meta property="og:image:width" content="1200">\n' +
'<meta property="og:image:height" content="630">\n' +
'<meta property="og:image:alt" content="' + esc(SITE_CONFIG.name + ' — remote and work from home jobs') + '">\n' +
(job.postedDate ? '<meta property="article:published_time" content="' + esc(isoDate(job.postedDate)) + '">\n' : '') +
(job.validThrough ? '<meta property="article:expiration_time" content="' + esc(isoDate(job.validThrough)) + '">\n' : '') +
'<meta property="article:section" content="' + esc(cat.name) + '">\n' +
job.skills.slice(0, 6).map((s) => '<meta property="article:tag" content="' + esc(s) + '">\n').join('') +
'\n' +
'<!-- X / Twitter -->\n' +
'<meta name="twitter:card" content="summary_large_image">\n' +
(twitter ? '<meta name="twitter:site" content="' + esc(twitter) + '">\n' : '') +
'<meta name="twitter:title" content="' + esc(title) + '">\n' +
'<meta name="twitter:description" content="' + esc(description) + '">\n' +
'<meta name="twitter:image" content="' + esc(ogImage) + '">\n' +
'\n' +
'<link rel="icon" href="../assets/images/favicon.svg" type="image/svg+xml">\n' +
'<link rel="apple-touch-icon" href="../assets/images/icon-180.png">\n' +
'<link rel="manifest" href="../site.webmanifest">\n' +
'<link rel="preload" href="../assets/data/jobs.json" as="fetch" crossorigin="anonymous">\n' +
'<link rel="stylesheet" href="../assets/css/style.css">\n' +
'<link rel="stylesheet" href="../assets/css/components.css">\n' +
'<link rel="stylesheet" href="../assets/css/responsive.css">\n' +
'\n' +
jsonLd('job-schema', jobPostingSchema(job)) + '\n' +
jsonLd('breadcrumb-schema', breadcrumbSchema(job)) + '\n' +
'</head>\n' +
'<body data-page="job" data-job-id="' + esc(job.id) + '" class="has-apply-bar">\n' +
chrome.header +
'<main id="main">\n' +
'  <section class="page-head">\n' +
'    <div class="container page-head__inner">\n' +
'      <nav class="breadcrumb" aria-label="Breadcrumb" data-breadcrumb>' + breadcrumbHTML(job) + '</nav>\n' +
'    </div>\n' +
'  </section>\n' +
'\n' +
'  <section class="section section--tight">\n' +
'    <div class="container">\n' +
'      <div class="detail-layout" data-job-article>\n' +
'        <article class="detail-main" data-job-detail data-prerendered="true">' + detailHTML(job) + '</article>\n' +
'        <aside class="detail-sidebar" data-job-sidebar aria-label="Job actions and summary">' + sidebarHTML(job) + '</aside>\n' +
'      </div>\n' +
'    </div>\n' +
'  </section>\n' +
'\n' +
(related.length
  ? '  <section class="section section--tight" data-related-section>\n' +
    '    <div class="container">\n' +
    '      <div class="section-head">\n' +
    '        <div class="section-head__group">\n' +
    '          <h2 class="section-head__title">Related Remote Jobs</h2>\n' +
    '          <p class="section-head__text">Similar roles based on category, job type and skills.</p>\n' +
    '        </div>\n' +
    '      </div>\n' +
    '      <div class="job-list job-list--grid" data-related-jobs>' + related.map(cardHTML).join('') + '</div>\n' +
    '    </div>\n' +
    '  </section>\n'
  : '  <section class="section section--tight" data-related-section hidden>\n' +
    '    <div class="container"><div class="job-list job-list--grid" data-related-jobs></div></div>\n' +
    '  </section>\n') +
'\n' +
'  <section class="section section--tight" data-recent-section hidden>\n' +
'    <div class="container">\n' +
'      <div class="section-head">\n' +
'        <div class="section-head__group">\n' +
'          <h2 class="section-head__title">Recently viewed</h2>\n' +
'          <p class="section-head__text">The last few jobs you opened, kept in this browser only.</p>\n' +
'        </div>\n' +
'      </div>\n' +
'      <div class="job-list job-list--grid" data-recent-list></div>\n' +
'    </div>\n' +
'  </section>\n' +
'</main>\n' +
'\n' +
'<div class="apply-bar" data-apply-bar hidden></div>\n' +
'\n' +
chrome.footer +
chrome.scripts +
'</body>\n' +
'</html>\n';
}

/* =============================================================================
   8. sitemap.xml
   ========================================================================== */
function buildSitemap(jobs) {
  const today = new Date().toISOString().slice(0, 10);
  const entry = (loc, changefreq, priority, lastmod) =>
    '  <url><loc>' + esc(loc) + '</loc>' +
    (lastmod ? '<lastmod>' + lastmod + '</lastmod>' : '') +
    '<changefreq>' + changefreq + '</changefreq><priority>' + priority + '</priority></url>';

  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!--',
    '  Generated by tools/build.js on ' + today + ' — re-run it after editing',
    '  assets/data/jobs.json or the domain in assets/js/config.js.',
    '-->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entry(SITE_URL + '/', 'daily', '1.0', today),
    entry(canonicalUrl('jobs.html'), 'daily', '0.9', today),
    entry(canonicalUrl('categories.html'), 'weekly', '0.8', today),
    ''
  ];

  CATEGORIES.forEach((c) => {
    lines.push(entry(canonicalUrl('category.html?category=' + encodeURIComponent(c.slug)), 'daily', '0.7', today));
  });
  lines.push('');

  /* One entry per job page — the reason this script exists. */
  jobs.forEach((job) => {
    lines.push(entry(canonicalUrl(job.pageUrl), 'weekly', '0.8', isoDate(job.postedDate) || today));
  });
  lines.push('');

  ['about.html', 'contact.html'].forEach((p) => lines.push(entry(canonicalUrl(p), 'monthly', '0.5')));
  ['privacy.html', 'terms.html', 'disclaimer.html'].forEach((p) => lines.push(entry(canonicalUrl(p), 'yearly', '0.3')));

  lines.push('</urlset>', '');
  return lines.join('\n');
}

/* =============================================================================
   9. Run
   ========================================================================== */
function main() {
  const raw = JSON.parse(readFile('assets/data/jobs.json'));
  const list = Array.isArray(raw) ? raw : Array.isArray(raw.jobs) ? raw.jobs : [];
  const jobs = list
    .map(normalize)
    .filter((j) => j.status === 'active')
    .sort((a, b) => dateValue(b.postedDate) - dateValue(a.postedDate));

  if (!jobs.length) {
    console.error('! No active listings found in assets/data/jobs.json — nothing to generate.');
    process.exit(1);
  }

  /* Two jobs sharing a slug would overwrite each other's page. */
  const seen = new Map();
  jobs.forEach((j) => {
    if (seen.has(j.slug)) {
      console.error('! Duplicate slug "' + j.slug + '" from ids ' + seen.get(j.slug) + ' and ' + j.id +
        '.\n  Give one of them a unique "id" (or a "slug") in jobs.json and re-run.');
      process.exit(1);
    }
    seen.set(j.slug, j.id);
  });

  const chrome = liftChrome();
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const written = new Set();
  jobs.forEach((job) => {
    const file = path.join(ROOT, job.file);
    fs.writeFileSync(file, pageHTML(job, jobs, chrome), 'utf8');
    written.add(path.basename(file));
  });

  /* Remove pages for listings that are gone, but never touch hand-written
     files: only pages carrying this script's marker are deleted. */
  let removed = 0;
  fs.readdirSync(OUT_DIR).forEach((name) => {
    if (!name.endsWith('.html') || written.has(name)) return;
    const full = path.join(OUT_DIR, name);
    if (fs.readFileSync(full, 'utf8').includes(MARKER)) {
      fs.unlinkSync(full);
      removed++;
    }
  });

  fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), buildSitemap(jobs), 'utf8');

  /* /remote-jobs/ itself is not a page — send it to the listing page. */
  const redirects = [
    '# Generated by tools/build.js — Cloudflare Pages reads this on deploy.',
    '/' + JOB_DIR + '/    ' + linkPath('/jobs.html') + '    301',
    '/' + JOB_DIR + '     ' + linkPath('/jobs.html') + '    301',
    ''
  ].join('\n');
  fs.writeFileSync(path.join(ROOT, '_redirects'), redirects, 'utf8');

  /* ---- report ---- */
  const noSchema = jobs.filter((j) => !jobPostingSchema(j));
  console.log('\n  ' + jobs.length + ' job page' + (jobs.length === 1 ? '' : 's') + ' written to /' + JOB_DIR + '/');
  if (removed) console.log('  ' + removed + ' page' + (removed === 1 ? '' : 's') + ' removed (listing no longer in jobs.json)');
  console.log('  sitemap.xml rebuilt with ' + (jobs.length + CATEGORIES.length + 8) + ' URLs');
  console.log('  _redirects written');
  console.log('\n  Example URL: ' + canonicalUrl(jobs[0].pageUrl));

  if (SITE_URL.includes('YOUR-DOMAIN')) {
    console.log('\n  ! assets/js/config.js still points at ' + SITE_URL);
    console.log('    Set your real domain there, then run this script again so the');
    console.log('    canonical tags and sitemap.xml carry the right host.');
  }
  if (SITE_CONFIG.demoMode) {
    console.log('\n  ! demoMode is true, so every generated page is noindex, nofollow.');
    console.log('    Set demoMode: false in assets/js/config.js once the listings are real.');
  }
  if (noSchema.length) {
    console.log('\n  ! ' + noSchema.length + ' page(s) have no JobPosting structured data because the');
    console.log('    listing is marked "demo": true (or is missing title/company/postedDate).');
    console.log('    Google must not be given markup for jobs that do not exist — remove the');
    console.log('    demo flag once the entry is a verified vacancy.');
  }
  console.log('');
}

main();
